### ISSUE TITLE
Doubts

### ISSUE THREAD

**Issue by e-labInnovations** [kmakise/Micromouse#2]
What is the use of that fan and 3D-printed parts?

Can you please check your telegram?

**Comment by mimo-10** [comment]
They use it to create a force that will counter the lift force. This will increase the pressure towards the surface, thus the car will be more sticky with the ground, this helps to control it when speed is high(drag force high also). This is all about encounter the aerodynamic forces. That's what I know if I'm wrong I hope u correct me. Have a nice day : )
